select * from album
select * from artist
select * from employee

# beginner level questions


Q1 : display all records from atrist table 

select * from artist 

Q2 : show all customers from india

select * 
from customer
where country = 'India'

Q3 : List all tracks with unit price greater than 1.99

select * from track
where unit_price > 0.99

Q4 : Find customers whose email ends with @gmail.com

select * 
from customer
where email like '%@gmail.com'

Q5 : Display all albums released by a specific artist

select * 
from album
where artist_id = '2'


Q6 : Show employees who are Sales Support Agents

select * 
from employee
where title = 'Sales Support Agent'

Q7 : Display customers sorted by first name (A–Z)

select * 
from customer
order by first_name asc


Q8 Count total number of customers

select count(*)
from customer

Q9 Find total number of tracks in the store

select sum(track_id) as total_tracks
from track

Q10 Calculate total revenue from all invoices

select count(total) as total_revenue
from invoice

Q11 Find the average track price

select avg(unit_price) as average_track_price 
from track

Q12 Count how many invoices each customer has generated

select customer_id, count(invoice_id) as invoice
from invoice
group by customer_id


Q13 Find the highest invoice total

select max(total) as highest_invoice
from invoice

Intermediate Level Queries
 *  GROUP BY & HAVING

Q14 Find total sales amount for each country

 select billing_country, sum (total) as total_sales
 from invoice
 group by billing_country
 order by total_sales desc

	
Q15 Find number of customers in each country

select country, count(*) as num_customers
from customer
group by country
order by num_customers desc

Q16 List countries having more than 5 customers

select country,  count(*) as total_customers
from customer
group by country
having count(*)>5

Q17 Find total revenue generated by each city

select billing_city, sum(total) as total_revenue
from invoice
group by billing_city
order by total_revenue desc

Q18 Find total tracks per genre

select genre_id, count(track_id) as total_track
from track
group by genre_id
order by count(track_id) desc

* JOIN Queries

Q19 Display customer name along with invoice details

select c.customer_id,c.first_name, c.last_name, i.billing_city,i.billing_state,i.billing_country, i.total
from customer as c
left join invoice as i 
on c.customer_id=i.customer_id
order by i.total desc nulls last

Q20 List all tracks with their album and artist name


select t.track_id, t.name, ar.name , a.title
from track as t
left join album as a
on t.album_id = a.album_id
left join artist as ar
on ar.artist_id=a.artist_id
order by t.track_id desc


Q21 Find invoice line items with track name and price

select i.invoice_line_id, i.invoice_id, i.track_id, i.unit_price, i.quantity, t.name
from invoice_line as i
join track as t
on i.track_id = t.track_id
order by i.unit_price desc 
 

Q22 Show employee names along with customers they support

select * from employee
select * from customer

select e.employee_id, e.first_name as emp_firstname, e.last_name as emp_lastname, c.customer_id, c.first_name as cust_firstname, c.last_name as cust_lastname, c.support_rep_id
from employee as e
left join customer as c
on e.employee_id = cast (c.support_rep_id as varchar )

Q23 Display genre name with total number of tracks


select g.name as genre_name, count(t.track_id) as total_tracks
from genre g
left join track as t
on g.genre_id = t.genre_id
group by g.name
order by count(t.track_id) desc


* Upper-Intermediate (Good for Resume)
* Business-Style Analysis Queries



Q24 Find top 5 customers by total spending


select c.customer_id,c.first_name, c.last_name, sum(i.total) as total_spending
from customer as c
join invoice as i
on c.customer_id = i.customer_id
group by c.customer_id,c.first_name,c.last_name
order by sum(i.total) desc
limit 5



Q25 Find top 5 selling tracks

select t.track_id, t.name as track_name, sum(il.unit_price * il.quantity) as total_price
from invoice_line as il
join track as t
on t.track_id = il.track_id
group by t.track_id,t.name
order by sum(il.unit_price * il.quantity) desc
limit 5










